name: "languages/rust/programming_rust/test-struct"

on:
  push:
    paths:
      - '.github/workflows/languages_rust_programming_rust_test-struct.yml'
      - 'languages/rust/programming_rust/test-struct/**'

permissions:
  contents: read

defaults:
  run:
    shell: bash
    working-directory: 'languages/rust/programming_rust/test-struct'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
      - uses: actions-rs/grcov@v0.1
        id: coverage
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.coverage.outputs.report }}
