name: Ruby

on:
  pull_request:
    paths:
      - '.github/workflows/ruby.yml'

jobs:
  test_ruby:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        ruby-version: ['2.7.2']
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: |
          ruby -v
          bundler -v
        shell: bash
      - run: |
          ruby -e 'puts Gem::Platform.local'
        shell: bash
