name: workflow_name
run-name: workflow_name ${{ inputs.target }}

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  test_workflow_name:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ inputs.target }}
